name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Her gece saat 00:00'da çalışır
  workflow_dispatch: # Manuel çalıştırmak için

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # 1. Reponu çek
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Yılan SVG dosyalarını üret
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: efekannn5
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      # 3. Değişiklikleri repoya kaydet
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate contribution grid snake"
          add: "output/*.svg"
